### ISSUE TITLE
reroute x on choose username

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#159]
actual behaviour: when i click the x button on "choose username", it goes to "restore account"
expected behaviour: when i click the x button on "choose username" it goed to "new here"

this is a change request, because in the wiki it is stated as follows:
"click x button route to stop signup"

**Comment by faffydee** [comment]
> actual behaviour: when i click the x button on "choose username", it goes to "restore account"
> expected behaviour: when i click the x button on "choose username" it goed to "new here"

When you hit the x, it does idd stop signup-process, which is idd by design.
But this issue made me think about it, and I think we could optimize it a litlle. So let's change it to this:

After hitting "create account" on the blue screen 'usr-view-create' (="You must be new here"), you get a new page which is basically a merge of 'choose username' and 'choose avatar'. That page will contain:
- Bodycopy: "choose avatar and username"
- an avatar + the upload-icon (as it is now on the 'usr-view-my-profile' pages)
- an inputfield with label 'username'
- a cancel(X) / next(V) btn duo

The X leads you directly back to 'usr-view-create' (="You must be new here.").
The V leads you to 'usr-pre-back' (="Great! You now have a Swarm City account."), from which the flow continues as is now.
