### ISSUE TITLE
Adjustments My Profile

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#254]
@n3xco did the page as designed but seeing it live, I think it still needs some improvements, the final result is not yet pleasing.
- [x] change padding 'top' in wide-layout: 16vh 12vw 10vh 12vw
- [x] add line below 'top'-div (similar line as below 'hashtagbox')
- [x] margin of btns: 10px instead of 14px

I'm looking into changing the `<display-profile-swr>` because this doesn't feel right, but this stil needs work. I'll add the changes (with a screenshot) in a comment on this issue once they're ready.

**Comment by xardass** [comment]
no button maxheight:

![image](https://user-images.githubusercontent.com/26218337/31130347-6f6e6b78-a857-11e7-95d1-1ea834b583ae.png)

Top needs padding for mobile too since you added the grey divider:
![image](https://user-images.githubusercontent.com/26218337/31130376-83397d3c-a857-11e7-91c1-4e888c13d683.png)
